FROM pytorch/pytorch:2.4.1-cuda12.4-cudnn9-devel

RUN apt-get update

# install tesseract and german language pack
RUN apt install -y tesseract-ocr libtesseract-dev
RUN apt-get install -y tesseract-ocr-deu


# install python dependencies
RUN pip install \
    pillow \
    transformers \
    fastapi \
    uvicorn \
    python-multipart \
    pytesseract

# pre load models
RUN python -c "from transformers import AutoModel, AutoTokenizer; AutoModel.from_pretrained('impira/layoutlm-document-qa'); AutoTokenizer.from_pretrained('impira/layoutlm-document-qa', clean_up_tokenization_spaces=True)"

WORKDIR /app
COPY . .

# # preload models
# RUN python load_models.py

# ENTRYPOINT [ "python", "run.py" ]
# ENTRYPOINT [ "/bin/bash" ]
ENTRYPOINT [ "uvicorn", "run:app", "--host", "0.0.0.0", "--port", "10000" ]