FROM python:3.10-slim-bullseye

RUN apt-get update

RUN pip install \
    fastapi \
    uvicorn \
    python-multipart \
    gradio_client \
    pillow


WORKDIR /app
COPY . .

ENTRYPOINT [ "uvicorn", "run:app", "--host", "0.0.0.0", "--port", "8080" ]