FROM pytorch/pytorch:2.4.1-cuda12.4-cudnn9-devel

RUN apt-get update

RUN pip install \
    pillow \
    timm \
    fastapi \
    uvicorn \
    nltk \
    python-multipart

RUN python -c "import timm; timm.create_model('tf_efficientnetv2_m.in21k', pretrained=True)"

RUN python -c "import nltk; nltk.download('wordnet')"

WORKDIR /app
COPY . .

# ENTRYPOINT [ "/bin/bash" ]
ENTRYPOINT [ "uvicorn", "run:app", "--host", "0.0.0.0", "--port", "10000" ]